module.exports = {
    "codes": ["QELx01",
        "QELx02",
        "QELx03",
        "QELx04",
        "QELx05",
        "QELx06",
        "QELx07",
        "QELx08",
        "QEAx01",
        "QEAx02",
        "QEAx03",
        "QEPx01",
        "QEPx02",
        "QEPx04",
        "QEPx05",
        "QEPx06",
        "QESx02",
        "QESx03",
        "QESx04",
        "QESx05",
        "QESx06",
        "QESx07",
        "QESx08",
        "QESx09",
        "QECx01",
        "QECx02",
        "QECx03",
        "QECx04",
        "QECx05",
        "QECx06",
        "QEMx01",
        "QEXx01",
        "QEXx02",
        "QEXx03"],
    "messages": [
        "You have exceeded your daily call limit as an anonymous user.",
        "You have exceeded your daily call limit as a registered user.",
        "You have exceeded your daily call limit as a subscriber.",
        "You have exceeded your 10-minute call limit as a registered user.",
        "You have exceeded your 10-minute call limit as a subscriber.",
        "You have requested too many rows of data.",
        "Your request query parameters are too long.",
        "The amount of data you are trying to return is too large. You need to narrow the data returned with filters.",
        "We could not recognize your API key. Please check your API key and try again. You can find your API key under your account settings.",
        "Your login credentials are invalid.",
        "You must have an API key to access this resource.",
        "You have attempted to view a protected resource in anonymous mode, i.e., without providing an API key.  Please register for a free Quandl account and then include your API key with your requests.",
        "You do not have permission to use this endpoint.",
        "You do not have permission to view this dataset OR you have exceeded your quota of free trials for this dataset. Please subscribe to this dataset to get more views or downloads.",
        "You have attempted to view a premium dataset in anonymous mode, i.e., without providing an API key. Please log in or register for a free Quandl account and then include your API key with your requests.",
        "You do not have access to view part of the data requested (e.g., column).",
        "You are missing a required parameter or its value is empty. Please check your parameters and try again.",
        "You have submitted incorrect parameters for creating/updating this resource. Please check your API call syntax and try again.",
        "You have submitted incorrect query parameters. Please check your API call syntax and try again.",
        "You have requested an unknown format. Please check the format you requested and try again.",
        "You have used an invalid cursor or page ID with your query. Please check your query and try again.",
        "You have used an unsupported operator for your query parameters. Please check and try again.",
        "You have tried to filter a column that is not available for filtering. Please remove and try again.",
        "The syntax of your query parameters is incorrect. Please check the syntax and try again.",
        "Unknown API route. We could not recognize the URL you requested. Please check your URL and try again.",
        "You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.",
        "We could not find the resource you requested. Please check your URL and try again.",
        "The referral code is invalid. Please try again.",
        "The URL you requested is incorrect. You may be presented with an alternative URL to use instead.",
        "You cannot make API calls to this dataset. This dataset has been deprecated. Please contact connect@quandl.com for further information.",
        "Something went wrong. Please try again. If you continue to have problems, please contact us at connect@quandl.com.",
        "The request took too long. Please try again later.",
        "We are experiencing connectivity issues. Please try again later.",
        "Something went wrong. Please try again. If you continue to have problems, please contact us at connect@quandl.com."
    ]
};